### ISSUE TITLE
Winter 21: Migrate to SObject.getErrors methods

### ISSUE THREAD

**Issue by jamessimone** [mitchspano/apex-trigger-actions-framework#1]
## Expected Behavior

Safe harbor, but seems likely to be included in Winter 21: https://releasenotes.docs.salesforce.com/en-us/winter21/release-notes/rn_apex_trackErrors.htm - this allows us to replace the usage of `ApexPages.getMessages()` with the new `.getErrors()` method on SObjects:

* In [MetadataTriggerHandlerTest](https://github.com/mitchspano/apex-trigger-actions-framework/blob/232103bda3526c8dfcb343b64e447dcb0b9b59bd/application/base/main/default/classes/MetadataTriggerHandlerTest.cls)
* In [ta_Opportunity_StageChangeRulesTest](https://github.com/mitchspano/apex-trigger-actions-framework/blob/232103bda3526c8dfcb343b64e447dcb0b9b59bd/application/opportunity-automation/main/default/classes/ta_Opportunity_StageChangeRulesTest.cls)
* In [ta_Opportunity_StageInsertRulesTest](https://github.com/mitchspano/apex-trigger-actions-framework/blob/232103bda3526c8dfcb343b64e447dcb0b9b59bd/application/opportunity-automation/main/default/classes/ta_Opportunity_StageInsertRulesTest.cls)
* And in the good old [Readme](https://github.com/mitchspano/apex-trigger-actions-framework/blob/232103bda3526c8dfcb343b64e447dcb0b9b59bd/README.md)

## Actual Behavior

`ApexPages` methods are used

## Notes

Happy to submit a PR for this after Winter 21 is released!

**Comment by mitchspano** [comment]
That would be great. The improved Apex error handling would be a great improvement over using `ApexPages` class.
