### ISSUE TITLE
Spring '23 Release: Changed Behaviour of Apex Static Variables

### ISSUE THREAD

**Issue by ozanbotanls** [mitchspano/apex-trigger-actions-framework#103]
Hey @mitchspano 

This is not an issue report per se, hence removed your template to freely write ;) 

Was just going through the Spring '23 release notes in detail and came across this one: 
- https://help.salesforce.com/s/articleView?id=release-notes.rn_apex_static_variables_interviews.htm&type=5&release=242
- https://help.salesforce.com/s/articleView?id=release-notes.rn_automate_flow_runtime_apex_static_variables.htm&type=5&release=242

I have my own bypass API implementation that stretches across triggers, flows, etc. and obviously, it is depending on a static variable that is maintained via an Apex class for a single transaction. Although the release notes specifically talk about **_PE-triggered_** flows, I feel like it is better to double-check and/or evaluate this in terms of record-triggered flows. 

From what I see, your framework relies on static variables in a similar fashion. So just wanted to give a heads-up ;) 

Cheers!

**Comment by mitchspano** [comment]
Hey @ozanbotanls,

Thank you so much for the heads up! I took a little bit of time to investigate the behavior differences between Platform-Event triggered flows and Trigger Action flows.

I created a scratch org on the next release preview:

```json
{
   "orgName": "Demo company",
   "edition": "Developer",
   "release": "preview",
   "features": []
}
```

Then, I put together a simple invocable apex action which increments and inserts accounts with increasing names and the running user’s Id

```java
public with sharing class Test {
  public static Integer i = 0;
  @InvocableMethod(
    category='Trigger Static Variable Test'
    label='Test Increment'
    description='Increments the count and creates accounts'
  )
  public static void increment(List<String> input) {
    List<Account> toInsert = new List<Account>();
    for (String s : input) {
      Test.i++;
      toInsert.add(new Account(Name = UserInfo.getUserId() + ' - ' + i));
    }
    insert toInsert;
  }
}
```

I then created a new platform event Test__e and enabled the Trigger Actions framework on the event:

```java
trigger TestTrigger on Test__e (after insert) {
  new MetadataTriggerHandler().run();
}
```

I then created a Platform Event triggered flow, and a Trigger Action flow which are functionally identical:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/18402464/211228847-43289c81-668b-4c98-9387-a37a1558b8ea.png">


<img width="716" alt="image" src="https://user-images.githubusercontent.com/18402464/211228857-dba1ce5e-8406-475b-a6ea-2fbd5dde8078.png">


Finally, to test the increment behavior, I executed the following code in the developer console:

```java
List<Test__e> testEvents = new List<Test__e>();
for (Integer i=0; i<25; i++) {
    testEvents.add(new Test__e());
}
List<Database.SaveResult> results = EventBus.publish(testEvents);
```

I then published these events nearly simultaneously  by logging in as a second user in an incognito window:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/18402464/211228865-0a5ef915-6a32-4124-ac25-6b8de16077bb.png">

There is a notable difference between Platform Event triggered flows, and Apex handled platform events (which includes trigger action flows): Platform Event triggered flows will be handled as the user which published them, however Apex triggers on platform events will run as the "Automated Process" user:

When taking a look at the accounts which are inserted, observe that the name counter is split into two chunks of 25 when handled by Platform Event trigger

<img width="719" alt="image" src="https://user-images.githubusercontent.com/18402464/211228885-892566df-b8ef-4b18-a613-0afaa6987132.png">

But when handled with Trigger Action flows, all accounts are inserted with one user and the count goes all the way up to 50

<img width="719" alt="image" src="https://user-images.githubusercontent.com/18402464/211228895-061fb9fe-7bbe-462b-a7fa-90709e5944c8.png">
 
This means that static variables will persist across multiple interviews of Trigger Action flows for platform events, and the static bypass mechanisms should stay in-tact even after the implementation of Spring 23 release.

This is a notable difference for platform event handling, but more of a consequence of the Apex vs Flow platform event handlers.
