### ISSUE TITLE
Support for flow collections?

### ISSUE THREAD

**Issue by robdavis-cs** [mitchspano/apex-trigger-actions-framework#106]
Hi!
While not necessarily an issue, I'm curious if there's a technical limitation that prevents being able to support passing in record collections to flows or if that is a feature that could be supported. I'd like to be able to do things like query related records, perform dml, etc in flows but can't with the one-at-a-time approach. I may want to take on that task but want to make sure it's not a fool's errand.
Thank you for all the work that's gone into this library!

**Comment by mitchspano** [comment]
Hello Rob - thanks for checking out the framework.

The system will automagically bulkify queries and DML operations for you!

Check out this sample flow action - it checks if the stage has changed, queries for the count of `OpportunityContactRole` records, then reads a cross-object relationship (`Opportunity.Account.Description`) to determine if the Account's description needs to be updated, and if it does, the parent Account will be updated.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/18402464/215940849-f3d7c42a-69bc-41a3-b03c-08cc47d24795.png">
<img width="459" alt="image" src="https://user-images.githubusercontent.com/18402464/215941185-72ee64b6-64db-45dd-927f-b69dde58161d.png">

There are quite a few places which could cause issues if not properly bulkified. 

Check out the following benchmark:
```java
System.SavePoint sp = Database.setSavepoint();

Contact luke = new Contact(
    FirstName = 'Luke',
    LastName = 'Skywalker'
);

Contact obi = new Contact(
    FirstName = 'Obi-Wan',
    LastName = 'Kenobi'
);

insert new List<Contact>{luke, obi};

List<Account> accounts = new List<Account>();
for (Integer i=0; i<200; i++) {
    accounts.add(new Account(Name = 'Foo ' + i));
}
insert accounts;

List<Opportunity> opps = new List<Opportunity>();
for (Integer i=0; i<200; i++) {
    opps.add(
        new Opportunity(
            AccountId = accounts[i].Id,
            Name = 'Test '+ i,
            StageName = 'Prospecting',
            CloseDate = Date.today()
        )
    );
}
insert opps;

List<OpportunityContactRole> ocrs = new List<OpportunityContactRole>();
for (Opportunity opp : opps) {
    opp.StageName = 'Qualification';
    ocrs.add(
        new OpportunityContactRole(
            OpportunityId = opp.Id,
            ContactId = luke.Id,
            Role = 'Business User'
        )
    );
    ocrs.add(
        new OpportunityContactRole(
            OpportunityId = opp.Id,
            ContactId = obi.Id,
            Role = 'Business User'
        )
    );
}
insert ocrs;

System.debug('BEFORE');
System.debug('getDmlStatements: ' + Limits.getDmlStatements());
System.debug('getDmlRows: ' + Limits.getDmlRows());
System.debug('getQueries: ' + Limits.getQueries());
System.debug('getQueryRows: ' + Limits.getQueryRows());
update opps;

System.debug('AFTER');
System.debug('getDmlStatements: ' + Limits.getDmlStatements());
System.debug('getDmlRows: ' + Limits.getDmlRows());
System.debug('getQueries: ' + Limits.getQueries());
System.debug('getQueryRows: ' + Limits.getQueryRows());
Long after = System.currentTimeMillis();

for (Account a : [SELECT Id, Description FROM Account WHERE Id IN :Accounts]) {
    System.assert.areEqual(
        'Count of Opportunity Contact Roles: 2',
        a.Description ,
        'Description populated incorrectly'
    );
}

Database.rollback(sp);
```

<img width="398" alt="image" src="https://user-images.githubusercontent.com/18402464/215943587-83bfa61f-5043-4487-91cd-541df6f398eb.png">

You can see that there is only one query execution to fetch the 400 `OpportunityContactRoles` and one additional DML operation, even though there are 200 flow interviews! This is the magic of the `Invocable.Action` class - it automagically bulkifies your actions for you just like record triggered flows.

Feel free to experiment and try it out!

**Comment by robdavis-cs** [comment]
Well that's pretty awesome @mitchspano . Thanks for enlightening me!

**Comment by robdavis-cs** [comment]
@mitchspano do you know if this behavior is documented anywhere? I'm trying to find it but no luck so far.

**Comment by mitchspano** [comment]
Unfortunately I do not have any links to supporting documentation ☹️.

Documentation for the `Invocable.Action` class is sparse at best. The only way I was able to get this to work was by lots of trial and error with that class.

**Comment by robdavis-cs** [comment]
You're right, it is very sparse. I attempted to get a spike bulk implementation going but wasn't able to. It looks like there's an issue with launching a flow where the input is a collection of records vs just the one. Here's the error message that I couldn't get around:

`System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Test_Case_Assignment: UNKNOWN_EXCEPTION - The input parameter "records" can't accept values of type SObjectList.: []  `
I [posted on Stackexchange](https://salesforce.stackexchange.com/questions/396213/unable-to-launch-flow-from-apex-with-record-collection-input) but don't have a ton of hope that I'll get any answers.
