### ISSUE TITLE
Guidance on bulkification of Flows?

### ISSUE THREAD

**Issue by msouther-lisc** [mitchspano/apex-trigger-actions-framework#110]
To be optimally helpful, I'd like to propose that the README should address the framework's ability to support queries and DML in Flow without crashing during bulk data operations. Based on some limited testing ([see related StackExchange thread](https://salesforce.stackexchange.com/questions/401447/invocable-actions-calling-flow-from-apex-with-bulk-data)), I believe the framework does leverage Salesforce Flow bulkification features via `Invocable.Action`.

Sadly, Salesforce themselves [do not address](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_Invocable_Action.htm#apex_class_Invocable_Action) whether calling a flow using `Invocable.Action` bulkifies the request. Regardless, it would be nice to have some insight into this up front before installing the framework. Thanks for your consideration!

**Comment by mitchspano** [comment]
Thanks for checking out the framework. You are correct, the `Invocable.Action` class will automatically bulkify the flow interviews for you. Check out this issue for more details.

https://github.com/mitchspano/apex-trigger-actions-framework/issues/106

I am hesitant to update the readme until Salesforce updates their documentation so I have something to reference, but the TLDR is that your flows will be bulkified, just like Record Triggered Flows.

While not particularly focused on bulkification, I do have a blog post which does a deep dive comparison of Trigger Action Flows and compares them with Record Triggered Flows - check out this blog post: https://www.mitchspano.com/blog/Trigger_Action_Flow

**Comment by msouther-lisc** [comment]
Good to know this has been thought of before! Makes sense, I guess you should probably take Salesforce's lead on documenting the behavior. Of course, the fact that it's undocumented may also mean that it's unsupported, which could be cause for some discomfort.

I guess I was hoping to hear that you had it from the horse's mouth that this will continue to work in the future, but absent that, I still really like what I'm seeing with this framework, and am still planning to promote it.
