### ISSUE TITLE
Record insert is triggger update actions with Insert actions.

### ISSUE THREAD

**Issue by Bharatsingh1991** [mitchspano/apex-trigger-actions-framework#123]
## Expected Behavior
While inserting a record only before insert and after Insert actions should execute.
## Actual Behavior
While inserting a record with before insert and after insert, before update and after update actions are also getting called.

## Steps to Reproduce the Problem

1. Insert any record that is having insert and update actions.

## Specifications

- Version:
- Platform:

**Comment by mitchspano** [comment]
Can you share any example code and metadata to help reproduce this issue?

Which version of the package are you using?

**Comment by Bharatsingh1991** [comment]
@mitchspano My bad I had setup fine logs and tested again it seems like there are some other processes that are executing and update lead and invoking the update event. Triggers Action framework working as expected. Thanks :)

**Comment by benjaminloerincz** [comment]
Yes, the framework is working fine. I can confirm this in a scratch org using this trigger action:

```
public with sharing class TA_AccountAction implements TriggerAction.BeforeInsert, TriggerAction.AfterInsert, TriggerAction.AfterUpdate {
    public void beforeInsert(List<Account> newList) {
        for (Account acc : newList) {
            acc.Name = 'BEFORE INSERT';
        }
    }

    public void afterInsert(List<Account> newList) {
        List<Task> tasks = new List<Task>();
        for (Account acc : newList) {
            Task t = new Task();
            t.Subject = 'AFTER INSERT';
            t.WhatId = acc.Id;
            tasks.add(t);
        }
        insert tasks;
    }

    public void afterUpdate(List<Account> newList, List<Account> oldList) {
        List<Task> tasks = new List<Task>();
        for (Account acc : newList) {
            Task t = new Task();
            t.Subject = 'AFTER UPDATE';
            t.WhatId = acc.Id;
            tasks.add(t);
        }
        insert tasks;
    }
}
```

After inserting the account, the name changed to BEFORE INSERT and the AFTER INSERT task was visible related to the account. Only on editing the account afterwards the second AFTER UPDATE task was visible.
