### ISSUE TITLE
General questions regarding the framework design and suggested implementation

### ISSUE THREAD

**Issue by jamesloughney** [mitchspano/apex-trigger-actions-framework#126]
Hi @mitchspano,

This is not an issue with the framework rather some questions I have regarding ways to use the framework and to help my understanding.

Firstly, I have recently started looking into the Trigger Actions Framework that you created. Thank you for your contributions to the community it is very much appreciated. 

Here are my questions below: 

1. I was wondering whether you ever intended that people using this framework would keep some record-triggered flow logic in place and only move some flows to auto-launched flows. Can you think of any advantages/disadvantages to not fully committing to the framework and moving all record-triggered flows over to auto-launched?

2. With regard to how I would write the flows, I understand that I should not call update records in the flows anymore, certainly not for the record that is being processed by the flow, but it is still okay to call update records/create records on other objects related or not related to the record being processed?

3. Would I be correct in thinking that I should not be updating any field on the record being processed in an after-insert / after-update trigger context? My assumption without running this would be that the updated value would not be saved.

4. Would you say that with this framework there is still room for a service-oriented or domain-driven design?

Thanks again for creating this. It is a really interesting design.

**Comment by mitchspano** [comment]
Let me do my best to answer these questions:

> 1. I was wondering whether you ever intended that people using this framework would keep some record-triggered flow logic in place and only move some flows to auto-launched flows. Can you think of any advantages/disadvantages to not fully committing to the framework and moving all record-triggered flows over to auto-launched?

The advantage of using Trigger Action flows is that _all_ of your logic is visible in one place and shares the same standardized bypass mechanisms. At this point, the only advantage of record triggered flows is that they can invoke an outbound message. I have written an article on this topic here - https://www.mitchspano.com/blog/Trigger_Action_Flow

> 2. With regard to how I would write the flows, I understand that I should not call update records in the flows anymore, certainly not for the record that is being processed by the flow, but it is still okay to call update records/create records on other objects related or not related to the record being processed?

Yes, it is totally fine to create/update/delete other records. Trigger Action Flows are bulkified just like record triggered flows, so performing DML on related records is totally fine. See [this comment](https://github.com/mitchspano/apex-trigger-actions-framework/issues/106#issuecomment-1411441389) for more details.

> 3. Would I be correct in thinking that I should not be updating any field on the record being processed in an after-insert / after-update trigger context? My assumption without running this would be that the updated value would not be saved.

Correct - mutations of the `record` variable during after context will not persist throughout the transaction. Fields in "after" context are read-only.

> 4. Would you say that with this framework there is still room for a service-oriented or domain-driven design?

There is always a place for layered architecture, but the Trigger Actions Framework greatly reduces the necessity for it when handling trigger logic. I would actually argue that creating the service and domain layers makes it _more_ challenging to partition your application into multiple packages, so proceed with caution.
