### ISSUE TITLE
Urgent: Production broke : oldMap is returning the same instance as Trigger.New

### ISSUE THREAD

**Issue by RIJIACloud** [mitchspano/apex-trigger-actions-framework#139]
## Expected Behavior
The new instance of the record and the old instance of the record should be different.

public static void trac_CasehandleAfterUpdate(List<Case> newCases, Map<Id,Case> oldMap){
   for(Case c : newCases){
      if(c.Status != oldMap.get(c.Id).Status){ // **This should return true**
         //perform some logic
      }
   }
}

## Actual Behavior
The new instance of the record and the old instance of the record is same.

public static void trac_CasehandleAfterUpdate(List<Case> newCases, Map<Id,Case> oldMap){
   for(Case c : newCases){
      if(c.Status != oldMap.get(c.Id).Status){ // **This is returning false**
         //perform some logic
      }
   }
}

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by mitchspano** [comment]
The code sample you've provided is not enough to pinpoint the source of this error as the trigger actions framework.

The [interfaces for the Trigger Actions framework](https://github.com/mitchspano/apex-trigger-actions-framework/blob/main/trigger-actions-framework/main/default/classes/TriggerAction.cls) don't even accept `oldMap` as an input - you would have to construct that yourself as is [explained in the readme](https://github.com/mitchspano/apex-trigger-actions-framework?tab=readme-ov-file#use-of-trigger-maps).


```shell
sf org create scratch \
  --definition-file config/project-scratch-def.json \
  --alias TAF \
  --set-default \
  --target-dev-hub DevHub
```

```shell
sf package install --package "04t3h000004juLuAAI" # latest package version
```

```java
trigger AccountTrigger on Account (
  before insert,
  after insert,
  before update,
  after update,
  before delete,
  after delete,
  after undelete
) {
  new MetadataTriggerHandler().run();
}
```

```java
public class TA_Account_Demo implements TriggerAction.BeforeUpdate {
  public static final string DESCRIPTION = 'Type was updated!';

  public void beforeUpdate(List<Account> newList, List<Account> oldList) {
    Map<Id, Account> oldMap = new Map<Id, Account>(oldList);
    for (Account a : newList) {
      if (a.Type != oldMap.get(a.Id).Type) {
        a.Description = DESCRIPTION;
      }
    }
  }
}
```

<img width="1160" alt="image" src="https://github.com/mitchspano/apex-trigger-actions-framework/assets/18402464/88199049-70c0-4abb-b82e-f73fb4f288ed">

```java
System.Savepoint sp = Database.setSavepoint();
Account acme = new Account(Name = 'Acme');
insert acme;
acme.Type = 'Partner';
update acme;
Assert.areEqual(
  TA_Account_Demo.DESCRIPTION,
  [SELECT Description FROM Account WHERE Id = :acme.Id].Description
);
Database.rollback(sp);
```

The system is working as intended - it properly detects old vs new as is demonstrated above.

**Comment by RIJIACloud** [comment]
Hi @mitchspano ,

Below is my method,

public void afterUpdate(List<SObject> newList, List<SObject> oldList) {
        CaseTriggerHelper.trac_CasehandleAfterUpdate((List<Case>) newList, new Map<Id, Case>((List<Case>) oldList));
    }

 public static void trac_CasehandleAfterUpdate(List<Case> newCases, Map<Id,Case> oldMap){
     for(Case c : newCases){
        if(c.Status != oldMap.get(c.Id).Status){ // This should return true
        //perform some logic
        }
     }
}

**Comment by mitchspano** [comment]
That could be caused by a previous action resetting the `Status` value on the case.
Without having access to the whole codebase, it's not possible to truly pinpoint the error within your application.

However, the framework itself is working fine.
