### ISSUE TITLE
Some Corrections for Documentation to "Avoid Repeated Queries" - otherwise you get an error: ExecutionException: Invalid conversion from runtime type

### ISSUE THREAD

**Issue by stern21** [mitchspano/apex-trigger-actions-framework#148]
## Expected Behavior
working as described in README for "Avoid Repeated Queries"

## Actual Behavior
Just after trying to follow the instructions on your documented in readme. By trying to save the Opportunity I get the message 
              ***********************
OpportunityTrigger: execution of BeforeInsert caused by: MetadataTriggerHandler.MetadataTriggerHandlerException: Please check the Trigger Action Custom Metadata for the BEFORE_INSERT context on the Opportunity sObject. The TA_Opportunity_Queries class does not implement the Trigger Action interface specified for the BEFORE_INSERT context. Class.MetadataTriggerHandler.handleException: line 505, column 1 Class.MetadataTriggerHandler.validateType: line 489, column 1 Class.MetadataTriggerHandler.executeActions: line 412, column 1 Class.MetadataTriggerHandler.beforeInsert: line 160, column 1 Class.TriggerBase.run: line 184, column 1 Trigger.OpportunityTrigger: line 10, column 1
            ***********************
lines might be not exactly these like in your packaged version , due to my try to find why.  And I found  that before it throw the error about the class isn't implemented, the actually issue is happened by trying to convert the Query Class to TriggerAction.BeforeInsert. 

[488]|e|"common.apex.runtime.impl.ExecutionException: Invalid conversion from runtime type TA_Opportunity_Queries to TriggerAction.BeforeInsert" 

Or I get the error 
      **********************
TA_Opportunity_Queries does not have a no-arg constructor
 System.TypeException: TA_Opportunity_Queries does not have a no-arg constructor

(System Code)
Class.MetadataTriggerHandler.executeActions: line 392, column 1
Class.MetadataTriggerHandler.beforeInsert: line 160, column 1
Class.TriggerBase.run: line 184, column 1
Trigger.OpportunityTrigger: line 10, column 1
19:29:33.1 (52416891)|FATAL_ERROR|System.TypeException: TA_Opportunity_Queries does not have a no-arg constructor
      ******************* 

This issue I could firstly overcome with changes on constructor accessor from **private** to **public**.  But after solving the issue above it acrually wasn't needed. 

## Steps to Reproduce the Problem

1. copied from readme the class: TA_Opportunity_Queries & the class TA_Opportunity_StandardizeName
2. Create Trigger on Opportunity: as described in readme
3. add entry to CMDT: sObject Trigger Setting and Trigger Action
4. open Opportunity
5. tick button "new " on Opportunity, fill requeired field and choose an account as reference 
6. try to save  and get an error  (see above) 

 The issue is happening at this line in MetadataTriggerHandler.validateType(   TriggerOperation context, Object triggerAction, String className   )

...
triggerAction = ((TriggerAction.BeforeInsert) triggerAction);
...
## Corrections 
That I would say because of using the TriggerAction.BeforeInsert in the inner class. My suggestion would be to use in CMDT: Trigger Action  TA_Opportunity_Queries**.Service** instead  of TA_Opportunity_Queries. since the super class doesn't have this function implemented :-) and isn't visible. 
<img width="660" alt="Trigger Framework_Correction to Query class using " src="https://github.com/mitchspano/apex-trigger-actions-framework/assets/115980085/6e135ace-71cd-4808-82c7-a3e39b6e2890">

## Specifications

- Version: 0.2.10
- Platform: Salesforce, Developer Edition

**Comment by mitchspano** [comment]
This is already included within the README:

https://github.com/mitchspano/apex-trigger-actions-framework?tab=readme-ov-file#avoid-repeated-queries

![image](https://github.com/mitchspano/apex-trigger-actions-framework/assets/18402464/b172de48-70d2-4f62-aa89-165f8f9b4cf9)
