### ISSUE TITLE
GitHub Salesforce Deploy Tool fails with "Could not find the repository 'apex-trigger-actions-framework'" error.

### ISSUE THREAD

**Issue by shahrier** [mitchspano/apex-trigger-actions-framework#155]
It is most likely an "andyinthecloud" issue as I see that is looking for the "master" branch (which has been renamed to the "main" branch)

<img width="1232" alt="Screenshot 2024-08-06 at 12 01 50 AM" src="https://github.com/user-attachments/assets/3a3b6e2f-3f6a-46f0-966a-72242b4e8ffc">

**Comment by mitchspano** [comment]
There is no master branch in the repository - only `main`.

You can explicitly set this in the SF deploy tool.

<img width="360" alt="image" src="https://github.com/user-attachments/assets/b66b4b1f-6a03-48cc-abb4-eaae7d13ce7a">

All things considered, I would recommend just using the package installation mechanism.
