### ISSUE TITLE
Deploy to Salesforce button not working for sandbox

### ISSUE THREAD

**Issue by saddankiSFDC** [mitchspano/apex-trigger-actions-framework#44]
## Expected Behavior
Deploy to Salesforce button should deploy code to sandbox
## Actual Behavior
Deploy to Salesforce button doesn't deploy code to sandbox
![image](https://user-images.githubusercontent.com/64547050/115161701-2ce4be80-a06d-11eb-99f8-f648d96b983a.png)

## Steps to Reproduce the Problem

1. Click Deploy to Salesforce
1. Specify branch as *master*
1. Error received

## Specifications

- Version:
- Platform:

**Comment by mitchspano** [comment]
Thanks for bringing this to my attention.

I think this is an issue with the Deploy to Salesforce Heroku app - https://github.com/afawcett/githubsfdeploy.
