### ISSUE TITLE
QUESTION - Working with sObjectChangeEvent

### ISSUE THREAD

**Issue by Picksley** [mitchspano/apex-trigger-actions-framework#46]
I've implemented the framework for objects which works brilliantly.

I'm going to need to use a Trigger on `CaseChangeEvent` as opposed to the sObject of `Case`. But the CaseChangeEvent action only supports the context 'after insert' - But would still encapsulate regular Create, Update operations as part of `EventBus.ChangeEventHeader.changeType`.

[See a valid example of Trigger using CaseChangeEvent here](https://developer.salesforce.com/docs/atlas.en-us.change_data_capture.meta/change_data_capture/cdc_add_trigger.htm)

When setting up the Metadata to use this, I'm unsure if I can use `Case` as the sObject Trigger Setting and still implement the CaseChangeEvent. Or even use CaseChangeEvent as the sObject Trigger Setting.

Has this been something anyone has had experience with already and could provide some knowledge?

**Comment by mitchspano** [comment]
Hey David,

The framework does work on ChangeEvents!

Perform the prerequisites defined [here](https://developer.salesforce.com/docs/atlas.en-us.change_data_capture.meta/change_data_capture/cdc_apex_triggers_prereqs.htm), then perform the following steps:

Create the trigger itself:
```java
trigger AccountChangeEventTrigger on AccountChangeEvent(after insert) {
  new MetadataTriggerHandler().run();
}
```

Create the Trigger Action.
```java
public with sharing class TA_AccountChangeTest implements TriggerAction.AfterInsert {
  public void afterInsert(List<AccountChangeEvent> newList) {
    List<Task> tasks = new List<Task>();

    // Iterate through each event message.
    for (AccountChangeEvent event : newList) {
      // Get some event header fields
      EventBus.ChangeEventHeader header = event.ChangeEventHeader;
      System.debug(
        'Received change event for ' +
        header.entityName +
        ' for the ' +
        header.changeType +
        ' operation.'
      );

      // Get account record fields
      System.debug('Account Name: ' + event.Name);
      System.debug('Account Phone: ' + event.Phone);

      // Create a followup task
      if (header.changetype == 'CREATE') {
        Task tk = new Task();
        tk.Subject =
          'Follow up on new account for record or group of records: ' +
          header.recordIds;
        // Explicitly set the task owner ID to a valid user ID so that
        // it is not Automated Process.
        // For simplicity, we set it to the CommitUser header field,
        // which is available for all operations.
        tk.OwnerId = header.CommitUser;
        tasks.add(tk);
      } else if ((header.changetype == 'UPDATE')) {
        // For update operations, iterate over the list of changed fields
        System.debug('Iterate over the list of changed fields.');
        for (String field : header.changedFields) {
          if (null == event.get(field)) {
            System.debug('Deleted field value (set to null): ' + field);
          } else {
            System.debug(
              'Changed field value: ' +
              field +
              '. New Value: ' +
              event.get(field)
            );
          }
        }
      }
    }

    // Insert all tasks in bulk.
    if (tasks.size() > 0) {
      insert tasks;
    }
  }
}


```

Setup the Metadata for the sObject Trigger Setting and the Trigger Action. Use the ChangeEvent name as the Object API Name - in this case it would be `AccountChangeEvent`:
![image](https://user-images.githubusercontent.com/18402464/116779570-a355c900-aa3c-11eb-8814-5fb7d194210b.png)

 
Insert or update records, and confirm that the system is working properly:

```
03:01:34.0 (121831781)|USER_DEBUG|[35]|DEBUG|Iterate over the list of changed fields.
03:01:34.0 (122159831)|USER_DEBUG|[40]|DEBUG|Changed field value: AccountNumber. New Value: 6511112222
03:01:34.0 (122320217)|USER_DEBUG|[40]|DEBUG|Changed field value: LastModifiedDate. New Value: 2021-05-01 10:01:33
```
 
![image](https://user-images.githubusercontent.com/18402464/116779580-abae0400-aa3c-11eb-9a57-c024ba002167.png)

Let me know if you have any other questions or issues using ChangeEvents.

-Mitch

**Comment by Picksley** [comment]
This is super cool, thanks so much @mitchspano !
