### ISSUE TITLE
Performance Issues When using GetOldRecord in Flow

### ISSUE THREAD

**Issue by mitchspano** [mitchspano/apex-trigger-actions-framework#56]
## Expected Behavior
I expect the `GetOldRecord` action to perform reasonably fast since it is not making any queries.

## Actual Behavior
`GetOldRecord` performs pretty slowly.

## Steps to Reproduce the Problem

Create a new scratch org
Push Trigger Actions Framework to the org
Enable Trigger Actions on the Case sObject
Create a new Trigger Action Flow on Case which calls `GetOldRecord` for each record:

![image](https://user-images.githubusercontent.com/18402464/122083668-ae836f00-cdc6-11eb-8019-745e7ff7480b.png)

Update 200 cases in the system.

```
Long before = System.currentTimeMillis();
update [Select ID FROM Case];
Long after = System.currentTimeMillis();
System.debug('MS to perform "GetOldRecord" on 200 cases : ' + (after - before));
```

```
10:34:48:863 USER_DEBUG [4]|DEBUG|MS to perform "GetOldRecord" on 200 cases : 15861
```

**Comment by benjaminloerincz** [comment]
I just took a closer look at the situation and was surprised that this Invocable Method consumes so much time. I tried to keep the transfer to the flow a bit simpler: Instead of the `Current Record`, you could also just pass the `Current Record Id`. Unfortunately, this small optimisation doesn't help much.

I suspect that quite a lot of performance is lost here due to serialisation and deserialisation between Apex and Flows.

Unfortunately you can't access `Trigger.old` within the Invocable Method, then you wouldn't have to pass oldList....

**Comment by mitchspano** [comment]
These performance issues are rather concerning. I am going to try a couple of things:

1) I wonder if there would be a meaning performance difference if we passed an individual record to the flow, then have the trigger kick off one flow per record. I doubt this would improve performance, but I'm going to try it out.

2) There may be a better way to fetch the old record without the use of an invocable method; perhaps with a subflow; perhaps just ensuring the newList and oldList share the same record ordering and finding the old record by the index of the current.

**Comment by surajp** [comment]
Looks like there might be a simple solve for this issue. You can create a static variable of type `Map<Id,SObject>` (say, `localOldMap`) and assign `Trigger.oldMap` to it in the static block in `TriggerActionFlow`. You then don't have to pass in the `oldList` to the flow and back, and can use the static variable `localOldMap` to get the old record.

**Comment by surajp** [comment]
Forgot to note in my previous comment that with this, even though we are seeing ~50% reduction in time taken, its still not great. One thing to try would be to directly pass in the record id instead of the `FlowInput` object as noted above.

**Comment by mitchspano** [comment]
FYI, I posted an [Idea in the community](https://trailblazer.salesforce.com/ideaView?id=0874V000000EMZRQA4) asking for the ability to **define an Apex data type which includes an sObject as an @AuraEnabled instance variable** for use in flows. If we could do that, then we could use an Apex defined data type in the flow like this:

```
public class TriggerRecord {
    @AuraEnabled sObject newRecord;
    @AuraEnabled sObject oldRecord;
}
```

This would allow us to iterate over a collection of `TriggerRecord` objects instead of injecting the `newList` and `oldList` variables at flow instantiation time and solve this issue.

**Comment by surajp** [comment]
You could pass in a single `newRecord` and `oldRecord` into the flow, into record variables currently. Is there a downside to that approach over using the Apex defined data type?

**Comment by mitchspano** [comment]
"You could pass in a single newRecord and oldRecord into the flow, into separate input record variables currently."

The issue with that approach would be that you then need to kick off up to 200 flow instances.

I did try this out and the code is present in [this branch](https://github.com/mitchspano/apex-trigger-actions-framework/commit/848b452abdce479ee44e467c346a041b5f73924c).
One thing which is nice about this approach is that it makes the approach for writing the flows a bit more approachable.

Here is an out of the box record triggered flow:
![image](https://user-images.githubusercontent.com/18402464/122630967-4ade9780-d08d-11eb-8d58-05a8171dff49.png)

And here is the same flow written in this new version of `TriggerActionFlow`:
![image](https://user-images.githubusercontent.com/18402464/122630975-69dd2980-d08d-11eb-91e7-31f70916c9b1.png)

This appears to operate with a better, with a performance time of about 3.5 seconds per 200 records, which is still rather unusable in my opinion, but there are some serious downfalls:
1) Writing the flows in this way will take about 3.5 seconds to execute no matter if you want to check old record values or not.
2) The "GetRecords" flow element would immediately break if more than 99 records were processed, since the SOQL would be executed for all of the unique flow instances.

**Comment by surajp** [comment]
I see your point. Makes sense. The Apex defined type would help get around that for sure. However, I do see a bigger issue with the approach of invoking flows from triggers in general and that is the inability to bulkiify record operations and invocable actions within the flow. As we have already seen, even soql-less invocables consume a significant amount of CPU time. I think there should be a disclaimer with the framework in general that it is not recommended to use the flow-based approach if you have invocable actions or database operations in your flow.

Also, regarding "The "GetRecords" flow element would immediately break if more than 99 records were processed, since the SOQL would be executed for all of the unique flow instances." like i said above, if you store the value of `Trigger.oldMap` in a static variable within the invocable class, you can use an operation like `staticOldMap.get(record.Id)` and avoid SOQL for getting the old record if you are invoking the flow once for each record. So, there wouldn't be an issue processing more than 99 records.

**Comment by mitchspano** [comment]
### Exploration
So I was playing around with this last night and I tried a few things:

1) **Perform an `n^2` loop over `oldList` and `newList` to find the old record.**
This actually works surprisingly well but would require a bit of repeated boilerplate flow elements:

![image](https://user-images.githubusercontent.com/18402464/122647861-eb63a480-d0eb-11eb-9e87-e4eda0320b76.png)

2) **Use the index in the `newList` to set values before insert/update instead of `newListAfterFlow`.**
The serialization of adding records to `newListAfterFlow` caused some performance issues, so I put the `newList` into a static variable made an invocable method which will set the values during before insert/update without the requirement of `newListAfterFlow`. This works a little better, and seems to provide a better experience for the admin.

```java
@invocableMethod(
  category='Trigger Action Flow'
  label='Set Values Before Insert/Update'
  description='Sets the value in the newList before insert or update'
)
public static void setNewFieldValueBeforeContext(
  List<SetNewFieldValueBeforeContextRequest> request
) {
  if (request.isEmpty() || request.size() > 1) {
    throw new TriggerActionFlowException(INVALID_REQUEST);
  }
  TriggerActionFlow.setEditableFields(
    TriggerActionFlow.newList[request[0].newListIndex],
    request[0].currentRecord
  );
}
```

![image](https://user-images.githubusercontent.com/18402464/122648495-2f0bdd80-d0ef-11eb-806e-e8c3c20db20e.png)


3) **Keep a static variable for `oldList` to reduce deserialization overhead**
This helps to improve the performance of the normal `getOldRecord` and access the old values one at a time. I changed the method to only require an Id to further reduce deserialization overhead.

```java
public static List<SObject> oldList;

public void beforeUpdate(List<SObject> newList, List<SObject> oldList) {
  TriggerActionFlow.oldList = oldList;
  if (!thisFlowIsBypassed()) {
    List<sObject> recordsNotYetProcessed = new List<sObject>();
    for (sObject record : newList) {
      if (
        TriggerBase.idToNumberOfTimesSeenBeforeUpdate.get(record.id) == 1 ||
        (allowRecursion == true)
      ) {
        recordsNotYetProcessed.add(record);
      }
    }
    Flow.Interview myFlow = Flow.Interview.createInterview(
      flowName,
      getFlowInput(recordsNotYetProcessed, oldList)
    );
    myFlow.start();
  }
}

@invocableMethod(
  category='Trigger Action Flow'
  label='Get Old Record'
  description='Returns the old version of a record from oldList'
)
public static List<sObject> getOldRecord(List<Id> request) {
  return new List<sObject>{
    new Map<Id, SObject>(TriggerActionFlow.oldList).get(request[0])
  };
}
```

![image](https://user-images.githubusercontent.com/18402464/122648801-64fd9180-d0f0-11eb-8f05-a423cfaa2942.png)

With a combination, we are able to get the time down to about 2.5-3.0 seconds.


### Findings

- Moving the `oldList` to a static variable had some pretty serious performance gains when compared to deserializing the record.
- It appears that invoking apex within a flow loop has a tax of about 1.5 seconds per 200 records.
- Serializing the full records from `newList` or `oldList` has a heavy tax as well.
- Whenever possible, we should check the current record's field state before getting the old record to check if the field has changed.
- We still need to determine if "Set Values Before Update" instead of adding to `newListAfterFlow`.
