### ISSUE TITLE
Question: Can multiple trigger actions be consolidated into one .cls file?

### ISSUE THREAD

**Issue by chazwatkins** [mitchspano/apex-trigger-actions-framework#61]
I found this framework recently and am blown away by the clarity it brings to trigger execution.  Kudos for building such a well-architected framework.  I can't wait for our team to adopt it.

### Use Case

 You have the same business logic that needs to be applied on `before insert` and `before update`.

### Using vanilla triggers
```apex
trigger AccountAddressCheckTrigger on Account (before insert, before update) {
    AccountBusinessLogic.checkAddress(Trigger.new);
}
```

### Using apex-trigger-actions-framework
This is my current understanding of how to do the same using this framework:

```apex
// AccountAddressCheckBeforeInsert.cls

public class AccountAddressCheckBeforeInsert implements TriggerAction.BeforeInsert {
    public void beforeInsert(Account[] newList) {
        AccountBusinessLogic.checkAddress(newList);
    }
}
```

```apex
// AccountAddressCheckBeforeUpdate.cls

public class AccountAddressCheckBeforeUpdate implements TriggerAction.BeforeUpdate {
    public void beforeUpdate(Account[] newList, Account[] oldList) {
        AccountBusinessLogic.checkAddress(newList);
    }
}
```

Is one file per trigger action required or can we consolidate it into the same file?

**Comment by mitchspano** [comment]
Great question Chaz!

You can (and should) combine the two classes into one by writing a single class which implements both interfaces.

```java
public class MyExample implements TriggerAction.BeforeInsert, TriggerAction.BeforeUpdate {
  public void beforeInsert(List<Case> newList){
    setDefaultValues(newList);
  }
  public void beforeUpdate(List<Case> newList, List<Case> oldList){
    setDefaultValues(newList);
  }
  private void setDefaultValues(List<Case> newList){...}
}
```

Then you just create one piece of custom metadata for each of the contexts on the sObject.

**Comment by chazwatkins** [comment]
Thanks for the help and explanation, Mitch.
